# Generated by Django 5.1.6 on 2025-02-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('N', 'not reviewed'), ('E', 'error'), ('A', 'accepted')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
